### ISSUE TITLE
autoload/db.php  多个配置，怎么切换

### ISSUE THREAD

**Issue by andy236726493** [hyperf/db-pgsql-incubator#3]
autoload/db.php里多个数据库配置读写分离，default和read，write， 

use Hyperf\DB\DB;

先用read, 再write
这里怎样写
$res = DB::query('SELECT * FROM USERS WHERE id = $1 AND nickname = $2;', [2, 'Hyperf']);

**Comment by andy236726493** [comment]
可以了

**Comment by Rodinio** [comment]
楼主  有mysql  pgsql 的多数据源怎么切换？
