### ISSUE TITLE
您好 ，hyperf 不支持这样的 pgsql  ？？

### ISSUE THREAD

**Issue by Rodinio** [hyperf/db-pgsql-incubator#4]
![55611651135507_ pic](https://user-images.githubusercontent.com/26924998/165714253-b5997cbc-2a51-4a8e-b8f4-710eb3eb1713.jpg)

**Comment by limingxinleo** [comment]
我记得有人写了一个。。。

**Comment by limingxinleo** [comment]
https://github.com/hyperf/database-pgsql-incubator

**Comment by Rodinio** [comment]
> https://github.com/hyperf/database-pgsql-incubator

您这个项目和 database-pgsql-incubator 是什么区别 ？或者差异？是单数据库 和 多数据库的
区别吗？
